// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xkaaruquhtarvjffseqz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhrYWFydXF1aHRhcnZqZmZzZXF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5MzU2MjMsImV4cCI6MjA1NzUxMTYyM30.qk3bz0QCsWT2hvz_gFWHUoGID0QyXAEcTy2kiPiZTbA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);